import Image from "next/image";
import Link from "next/link";
import { Metadata } from "next";
import Container from "@/components/common/Container";
import Button from "@/components/common/Button";
import SectionSpacer from "@/components/common/SectionSpacer";

export const metadata: Metadata = {
  title: "The Ultimate Guide to Surge Protection for Utility-Scale Solar Systems | Ksquare Energy",
  description:
    "As PV installations scale to utility capacities, learn the precision engineering protocols required to safeguard high-voltage DC arrays against lightning-induced surges and switching transients.",
};

const toc = [
  { id: "introduction", label: "Introduction" },
  { id: "what-is-mcb", label: "What is an MCB?" },
  { id: "how-mcb-works", label: "How MCB Works" },
  { id: "specifications", label: "Technical Specifications" },
  { id: "real-world-example", label: "Real-World Example" },
  { id: "faqs", label: "FAQs" },
];

const specs = [
  { label: "Max. Continuous Operating Voltage (Uc)", value: "275V AC" },
  { label: "Max. Discharge Current (Imax)", value: "40kA (8/20µs)" },
  { label: "Voltage Protection Level (Up)", value: "≤1.5kV" },
  { label: "Response Time", value: "<25ns" },
  { label: "SPD Type / Test Class", value: "Type 2 / Class II" },
  { label: "Number of Poles", value: "4P (3+NPE)" },
];

const faqs = [
  {
    q: "What are Solar Inverters?",
    a: "Solar inverters convert the DC electricity generated by solar panels into AC electricity, which is used to power your appliances and devices.",
  },
  {
    q: "What is the difference between a hybrid and a grid-tied solar inverter?",
    a: "A grid-tied inverter feeds power directly to the grid and shuts down during an outage, while a hybrid inverter can also charge a battery and continue supplying power when the grid is down.",
  },
  {
    q: "How many solar panels should I connect with my solar inverter?",
    a: "The number of panels depends on the inverter's rated DC input capacity and voltage window. Our engineers size the string configuration during the site survey to match your inverter model.",
  },
  {
    q: "What is the ideal number of solar panels for my solar inverter?",
    a: "Ideally, the combined panel wattage should be close to the inverter's rated AC output, with some allowance for de-rating losses due to temperature and wiring.",
  },
  {
    q: "How much can I reduce my electricity bill with a Ksquare solar inverter?",
    a: "Most residential and commercial customers see a significant reduction in their grid electricity bill, with exact savings depending on system size, local tariffs and net metering policy.",
  },
];

export default async function BlogDetailPage({ params }: { params: Promise<{ slug: string }> }) {
  await params;

  return (
    <main className="w-full bg-white font-archivo">
      {/* Breadcrumb */}
      <Container maxWidth="1800" className="pt-[90px] lg:pt-[130px] flex items-center flex-wrap gap-[10px]">
        <Link href="/" className="font-archivo text-[16px] lg:text-[20px] text-[#333333] hover:text-primary leading-[28px] transition-colors">
          Home
        </Link>
        <svg width="5" height="10" viewBox="0 0 5 10" fill="none"><path d="M1 1L4 5L1 9" stroke="#333333" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" /></svg>
        <Link href="/blog" className="font-archivo text-[16px] lg:text-[20px] text-[#333333] hover:text-primary leading-[28px] transition-colors">
          Blog
        </Link>
        <svg width="5" height="10" viewBox="0 0 5 10" fill="none"><path d="M1 1L4 5L1 9" stroke="#333333" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" /></svg>
        <span className="font-archivo text-[16px] lg:text-[20px] text-primary leading-[26px] truncate max-w-[400px]">
          Surge Protection Guide
        </span>
      </Container>

      <SectionSpacer size={60} />

      {/* Hero */}
      <Container maxWidth="1800">
        <div className="flex flex-col xl:flex-row items-stretch gap-[40px]">
          <div className="relative w-full xl:w-[900px] aspect-[900/615] rounded-[16px] overflow-hidden shrink-0">
            <Image
              src="/assets/blog/detail_hero.png"
              alt="Utility-scale solar array with surge protection"
              fill
              className="object-cover"
              priority
            />
          </div>
          <div className="flex flex-col gap-[24px] w-full justify-center">
            <h1 className="font-archivo text-[36px] lg:text-[52px] leading-[1.15] font-medium text-primary">
              The Ultimate Guide to Surge Protection for Utility-Scale Solar Systems
            </h1>
            <p className="font-archivo text-[17px] leading-[26px] text-[#666666] text-justify">
              As PV installations scale to utility capacities, the risk of lightning-induced surges and switching transients increases exponentially. Learn the precision engineering protocols required to safeguard high-voltage DC arrays.
            </p>
            <div className="flex items-center gap-[12px]">
              <div className="relative w-[40px] h-[40px] rounded-full overflow-hidden shrink-0">
                <Image src="/assets/blog/detail_author.png" alt="Kuldip Sorathiya" fill className="object-cover" />
              </div>
              <span className="font-archivo text-[17px] text-[#333333]">Kuldip Sorathiya</span>
              <span className="w-px h-[16px] bg-[#333333]" />
              <span className="font-archivo text-[17px] text-[#333333]">Sep 15, 2026</span>
            </div>
          </div>
        </div>
      </Container>

      <SectionSpacer size={100} />

      {/* Content + Sidebar */}
      <Container maxWidth="1800">
        <div className="flex flex-col-reverse xl:flex-row items-start gap-[40px] xl:gap-[60px]">
          {/* Sidebar TOC */}
          <aside className="hidden xl:flex flex-col gap-[32px] w-[360px] shrink-0 bg-[#EFF0F6] p-[24px] sticky top-[110px]">
            <span className="font-archivo text-[24px] text-[#333333]">Contents</span>
            <nav className="flex flex-col gap-[12px]">
              {toc.map((item, i) => (
                <a
                  key={item.id}
                  href={`#${item.id}`}
                  className={`font-archivo text-[20px] leading-[26px] pl-[16px] py-[4px] border-l-2 transition-colors ${
                    i === 0
                      ? "border-primary text-primary"
                      : "border-transparent text-[#666666] hover:text-primary hover:border-primary"
                  }`}
                >
                  {item.label}
                </a>
              ))}
            </nav>
          </aside>

          {/* Article Body */}
          <div className="flex flex-col gap-[64px] w-full">
            <section id="introduction" className="flex flex-col gap-[24px] scroll-mt-[110px]">
              <h2 className="font-archivo text-[28px] lg:text-[40px] leading-[1.2] text-[#333333]">
                Difference Between SPD and MCB &mdash; Complete Guide
              </h2>
              <p className="font-archivo text-[17px] leading-[26px] text-[#666666]">
                Electrical protection is an extremely important part of establishing the safety, reliability and life of any electrical system. Protective devices help prevent electrical faults, equipment damage and even fire in homes, offices, factories or solar installations.
              </p>
              <p className="font-archivo text-[17px] leading-[26px] text-[#666666]">
                The Surge Protection Device (SPD) and the Miniature Circuit Breaker (MCB) are both regarded as two of the most essential protection appliances in modern electrical systems. Both are used to protect equipment, but they are designed to address different kinds of electrical problems.
              </p>
            </section>

            <section id="what-is-mcb" className="flex flex-col gap-[24px] scroll-mt-[110px]">
              <h2 className="font-archivo text-[28px] lg:text-[40px] leading-[1.2] text-[#333333]">
                What is an MCB (Miniature Circuit Breaker)?
              </h2>
              <p className="font-archivo text-[17px] leading-[26px] text-[#666666]">
                A Miniature Circuit Breaker (MCB) is a safety device that automatically de-energizes an electric circuit upon detecting an overload or short circuit. In simple terms, it works like a resettable fuse that trips before excess current can damage your wiring and equipment.
              </p>
            </section>

            <section id="how-mcb-works" className="flex flex-col gap-[24px] scroll-mt-[110px]">
              <h2 className="font-archivo text-[28px] lg:text-[40px] leading-[1.2] text-[#333333]">
                How MCB Works
              </h2>
              <p className="font-archivo text-[17px] leading-[26px] text-[#666666]">
                When the electrical current flowing through a circuit exceeds its rated value, heat builds up within the MCB. This heat triggers a tripping mechanism that breaks the circuit. The MCB responds instantly to a short circuit, helping prevent equipment damage or fire.
              </p>
            </section>

            <section id="specifications" className="flex flex-col gap-[24px] scroll-mt-[110px]">
              <h2 className="font-archivo text-[28px] lg:text-[40px] leading-[1.2] text-[#333333] text-center">
                Technical Specifications
              </h2>
              <div className="w-full overflow-x-auto border border-[#DDDDDD]">
                <table className="w-full min-w-[500px] border-collapse">
                  <thead>
                    <tr className="bg-primary">
                      <th className="text-left font-archivo text-[20px] lg:text-[24px] font-normal text-white p-[16px_24px]">Parameters</th>
                      <th className="text-left font-archivo text-[20px] lg:text-[24px] font-normal text-white p-[16px_24px]">Value</th>
                    </tr>
                  </thead>
                  <tbody>
                    {specs.map((row) => (
                      <tr key={row.label} className="border-b border-[#DDDDDD]">
                        <td className="font-archivo text-[16px] lg:text-[17px] font-medium text-primary p-[16px_24px] align-top">{row.label}</td>
                        <td className="font-archivo text-[16px] lg:text-[18px] text-[#666666] p-[16px_24px] align-top">{row.value}</td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            </section>

            <section id="real-world-example" className="flex flex-col gap-[24px] scroll-mt-[110px]">
              <h2 className="font-archivo text-[28px] lg:text-[40px] leading-[1.2] text-[#333333]">
                Real-Life Example &mdash; Renewable Energy Installation
              </h2>
              <p className="font-archivo text-[17px] leading-[26px] text-[#666666]">
                Solar energy farms are unique among industrial facilities due to their large physical footprint and exposure to atmospheric phenomena. The interconnected nature of DC strings and AC collection networks creates multiple entry points for high-energy surges that can disrupt production for weeks if left unprotected.
              </p>
            </section>

            {/* Author bio */}
            <div className="flex flex-col sm:flex-row items-center gap-[24px] p-[24px] border border-primary">
              <div className="relative w-[100px] h-[100px] sm:w-[150px] sm:h-[150px] rounded-full overflow-hidden border-[3px] border-primary shrink-0">
                <Image src="/assets/blog/detail_author.png" alt="Kuldip Sorathiya" fill className="object-cover" />
              </div>
              <div className="flex flex-col gap-[8px] text-center sm:text-left">
                <h3 className="font-archivo text-[24px] text-[#333333]">Kuldip Sorathiya</h3>
                <p className="font-archivo text-[17px] leading-[26px] text-[#666666]">
                  Kuldip Sorathiya is a Senior Electrical Engineer at Ksquare Energy, specialising in AC and DC surge protection, MCBs and fuse solutions for solar and industrial installations. He leads Ksquare&apos;s engineering effort to deliver safer, more reliable power protection systems across every project.
                </p>
              </div>
            </div>

            {/* FAQ */}
            <div id="faqs" className="flex flex-col gap-[24px] scroll-mt-[110px]">
              <div className="flex flex-col gap-[8px]">
                <h2 className="font-jost text-[32px] lg:text-[48px] leading-[1.15] text-primary font-normal">
                  Frequently Asked <span className="font-recia italic font-medium">Questions</span>
                </h2>
                <p className="font-archivo text-[17px] leading-[26px] text-[#666666] max-w-[700px]">
                  Common questions about solar inverters, sizing and savings.
                </p>
              </div>
              <div className="flex flex-col gap-[16px]">
                {faqs.map((item, index) => (
                  <details key={item.q} className="group border-b border-[#DDDDDD] pb-[16px]" open={index === 0}>
                    <summary className="flex items-start justify-between gap-[24px] cursor-pointer list-none [&::-webkit-details-marker]:hidden">
                      <span className="font-archivo text-[18px] lg:text-[24px] leading-[1.3] text-[#333333]">
                        {item.q}
                      </span>
                      <span className="font-archivo text-[24px] text-[#333333] shrink-0 group-open:hidden">+</span>
                      <span className="font-archivo text-[24px] text-[#333333] shrink-0 hidden group-open:block">-</span>
                    </summary>
                    <p className="font-archivo text-[16px] lg:text-[17px] leading-[26px] text-[#666666] mt-[16px]">
                      {item.a}
                    </p>
                  </details>
                ))}
              </div>
            </div>
          </div>
        </div>
      </Container>

      <SectionSpacer size={150} />

      {/* CTA Banner */}
      <section className="relative w-full overflow-hidden">
        <div className="absolute inset-0 bg-primary" />
        <div className="hidden xl:flex absolute right-[80px] top-0 bottom-0 items-center opacity-90 pointer-events-none">
          <Image
            src="/assets/download-resources/cta_graphic.svg"
            alt=""
            width={505}
            height={312}
            className="object-contain"
            aria-hidden="true"
          />
        </div>
        <Container maxWidth="1600" className="relative z-10 py-[80px] lg:py-[110px]">
          <div className="flex flex-col gap-[24px] max-w-[1025px]">
            <div className="flex flex-col gap-[8px]">
              <h2 className="font-jost text-[36px] lg:text-[60px] leading-[1.15] text-white font-normal">
                Get bulk pricing on <span className="font-recia italic font-medium">Solar BOS Components</span>
              </h2>
              <p className="font-archivo text-[16px] lg:text-[17px] leading-[26px] text-[#EDF3FF] max-w-[700px]">
                Whether you need certified solar components, OEM manufacturing, or complete rooftop solar solutions, our team is ready to help.
              </p>
            </div>
            <div className="flex flex-wrap items-center gap-[16px]">
              <Button variant="outline" href="/contact" showDot>
                Request a Quote
              </Button>
              <Button variant="outline" href="/contact" showDot>
                Talk to Our Experts
              </Button>
            </div>
          </div>
        </Container>
      </section>
    </main>
  );
}
